export const puppyList = [
    {
      id: 1,
      name: "Sir Waggington",
      email: "sir-wag@email.com",
      isCute: "yes",
      age: 5,
      ownerId: 1,
      tricks: [
        { id: 2, title: "Lay Down" },
        { id: 3, title: "Jump through flaming hoop" },
      ],
      imgUrl: "https://muttville.org/images/mutts/107/0/1/107019-100001-lg.jpg",
    },
    {
      id: 2,
      name: "Fiona Penny Pickles",
      email: "pick-your-pennies@email.com",
      isCute: "absolutely",
      age: 6,
      ownerId: 1,
      tricks: [],
      imgUrl: "https://cdn.akc.org/content/article-body-image/cav_puppy.jpg",
    },
    {
      id: 3,
      name: "Professor Wagglesworth",
      email: "waggie@email.com",
      isCute: "but of course",
      age: 6,
      ownerId: 2,
      tricks: [{ id: 1, title: "Sit" }],
      imgUrl: "https://media.12news.com/assets/KPNX/images/fe20533c-37db-4c4d-8609-ae15912a1f3d/fe20533c-37db-4c4d-8609-ae15912a1f3d_1920x1080.jpg",
    },
    {
      id: 4,
      name: "Sergeant Barkowitz",
      email: "the-sarge@email.com",
      isCute: "perchance...",
      age: 4,
      ownerId: 2,
      tricks: [{ id: 2, title: "Lay Down" }],
      imgUrl: "https://media.defense.gov/2020/Mar/13/2002264576/825/780/0/200313-F-AR942-0359.JPG",
    },
    {
      id: 5,
      name: "Captain Sniffer",
      email: "capn-sniff@email.com",
      isCute: "heckin of course",
      age: 7,
      ownerId: 3,
      tricks: [],
      imgUrl: 'https://cdn.shopify.com/s/files/1/0593/5408/7620/files/cool-captain-crusoe-the-dachshund1.jpg',
    },
    {
      id: 6,
      name: "Miss Furbulous",
      email: "miss-furby@email.com",
      isCute: "no, shes furbulous, clearly",
      age: 1,
      ownerId: 3,
      tricks: [],
      imgUrl: "https://www.talenthounds.ca/wp-content/uploads/formidable/pii1.jpg",
    },
    {
      id: 7,
      name: "Alfred von Wigglebottom",
      email: "alfie@email.com",
      isCute: "a distinguished pup",
      age: 2,
      ownerId: 3,
      tricks: [],
      imgUrl: "https://i0.wp.com/theverybesttop10.com/wp-content/uploads/2014/02/Top-10-Best-Images-of-Dogs-Wearing-Monocles-10.jpeg?resize=600%2C746&ssl=1",
    },
  ];